remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-seo-tag

minima:
  skin: dark
  hide_site_feed_link: true

title: "Garrett Campbell's Personal Site"
description: Hosting personal project blogs and more!

author:
  name: Garrett Campbell


